### ISSUE TITLE
Debugging?

### ISSUE THREAD

**Issue by ericbarnes** [aniftyco/followers-to-list#2]
I basically know nothing about running node apps like this and for me the list is being created but no users are being added. What is the best way of debugging what is going on?  Totally newb here. 😄

**Comment by joshmanders** [comment]
hmmm, it should be using promises all the way through and the catch statement in `bin/go` should catch any errors and log them out to you.

**Comment by ericbarnes** [comment]
Here's what I'm getting: 

<img width="445" alt="screen shot 2017-06-26 at 2 19 49 pm" src="https://user-images.githubusercontent.com/116662/27553839-90a03086-5a7a-11e7-8030-1f8b72bb60a4.png">

The list is added, but no users: 

<img width="283" alt="screen shot 2017-06-26 at 2 19 41 pm" src="https://user-images.githubusercontent.com/116662/27553866-9d533ba2-5a7a-11e7-8de6-0cb0f2f6a457.png">

**Comment by joshmanders** [comment]
Ok, I fixed it, and made `private` configurable.

`bin/go ericlbarnes` defaults to public but `bin/go ericlbarnes private` makes it private.
